### ISSUE TITLE
ReputMessageService question ? the servicce is a dispatch thread . dispatch log to consumerqueue and index . why dont use wait() notify() ?? 

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#413]
> 
        public void run() {
            DefaultMessageStore.log.info(this.getServiceName() + " service started");

            while (!this.isStoped()) {
                try {
                    Thread.sleep(1);
                    
                    this.doReput();
                } catch (Exception e) {
                    DefaultMessageStore.log.warn(this.getServiceName() + " service has exception. ", e);
                }
            }

            DefaultMessageStore.log.info(this.getServiceName() + " service end");
        }

**Comment by a11123939** [comment]
And  mq thread model have design doc ??

**Comment by Jaskey** [comment]
1. In my opinon, this thread is busy enough so most of the time it should be working , if use notify , much more inter-thread communication is involved,which is acutully an unnessecary cost when writing is busy.

2. Easy. And ,enough.

**Comment by vongosling** [comment]
The above answer works well. Notify and Wait is a thread collaboration primitive. As the opposite of your answer, i wonder know how to use wait and notify correctly in your code? The following things must be remembered:
#### Use notifyAll instead of notify if you expect that more than one thread will be waiting for a lock.
#### The wait and notify methods must be called in a synchronized context. like the following code snippet:

    synchronized (oneObject) {
       someObject.wait();
    }

    /* different thread / object */
    synchronized (oneObject) {
        someObject.notify();
    }
#### Always call the wait() method in a loop because if multiple threads are waiting for a lock and one of them got the lock and reset the condition, then the other threads need to check the condition after they wake up to see whether they need to wait again or can start processing.
#### Use the same object for calling wait() and notify() method; every object has its own lock so calling wait() on object A and notify() on object B will not make any sense.

**Comment by a11123939** [comment]
ReputMessageService extends ServiceThread
ServiceThread has the function wakeup() and waitForRunning() function .
ReputMessageService why dont use wakeup() and waitForRunning().

ReputMessageService may waste cpu time when mq load is low .

**Comment by Jaskey** [comment]
@a11123939 

As to my comment  "#2" , you can't granteer 

> you can't guarantee that generating consume queue can catch up, so even though you use wait/notify, a while loop with sleep/time_waited is still nessacerry

so if you want a low latency response, at last, the waifForRunning(sleeptime) will be eventually equals to 1ms, which makes no sense for wait/notify usage

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0
